language: generic
dist: xenial
sudo: required

install:
  - wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y powershell

script:
  - bash ./test.sh
